#!/usr/bin/env python3
"""Test script for search engine - simulate the exact scenario user reported."""
import sys
import os
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('test')

# Add to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import the search engine
from search_engine import SearchEngine

# ── Build a test scenario ────────────────────────────────────
# Simulate OCR results where the text is generated by OCR
# Chinese chars might be recognized character by character

class MockPdfEngine:
    """Mock PDF engine with text_pages."""
    def __init__(self):
        self.text_pages = {}
    
    def search_text(self, query, case_sensitive=False, exact_match=False):
        """Simple substring search on text_pages."""
        results = []
        for pn, text in self.text_pages.items():
            search_text = text if case_sensitive else text.lower()
            search_query = query if case_sensitive else query.lower()
            if search_query in search_text:
                idx = search_text.find(search_query)
                start = max(0, idx - 30)
                end = min(len(search_text), idx + len(search_query) + 30)
                results.append({
                    'page': pn + 1,
                    'text': text[start:end].strip().replace('\n', ' '),
                    'source': '文字层',
                })
        return results

# Scenario 1: OCR produces individual characters per line (most common)
# e.g., OCR outputs: [{'text':'王'}, {'text':'麻'}, {'text':'子'}, {'text':'张三'}, ...]
print("=" * 60)
print("TEST 1: OCR outputs split characters per line")
print("=" * 60)

se = SearchEngine()

# Simulate page 1: OCR sees characters individually
se.add_ocr_results(0, [
    {'text': '王'},
    {'text': '麻'},
    {'text': '子'},
    {'text': '张三'},
    {'text': '李四'},
])

# Simulate page 2: OCR sees full name in one line
se.add_ocr_results(1, [
    {'text': '王麻子'},
    {'text': '张三'},
])

# Test search - single char
print("\n--- Search '王' ---")
r = se.search('王')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

# Test search - full name
print("\n--- Search '王麻子' ---")
r = se.search('王麻子')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

if not r:
    print("  ❌ EMPTY RESULT! This is the bug the user reported.")

# Scenario 2: Text layer has the name as contiguous text
print("\n" + "=" * 60)
print("TEST 2: Text layer has full name, OCR has split chars")
print("=" * 60)

se2 = SearchEngine()
mock_pdf = MockPdfEngine()
mock_pdf.text_pages = {
    0: "这是第1页内容，包含王麻子、张三和李四的信息。",
    1: "这是第2页内容，包含张三和王麻子的信息。",
}
se2.set_pdf_engine(mock_pdf)

# Also add split OCR results
se2.add_ocr_results(0, [
    {'text': '第1页内容'},
    {'text': '包含'},
    {'text': '王'},
    {'text': '麻'},
    {'text': '子'},
])

print("\n--- Search '王麻子' ---")
r = se2.search('王麻子')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

if not r:
    print("  ❌ EMPTY RESULT!")

# Scenario 3: Only OCR, chars on separate lines, every page has all chars
print("\n" + "=" * 60)
print("TEST 3: Only OCR, split chars, '王麻子' on every page")
print("=" * 60)

se3 = SearchEngine()
for pg in range(3):
    se3.add_ocr_results(pg, [
        {'text': f'第{pg+1}页'},
        {'text': '王'},
        {'text': '麻'},
        {'text': '子'},
        {'text': '其他内容'},
    ])

print("\n--- Search '麻子' ---")
r = se3.search('麻子')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

print("\n--- Search '王' ---")
r = se3.search('王')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

print("\n--- Search '王麻子' ---")
r = se3.search('王麻子')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

if not r:
    print("  ❌ EMPTY RESULT! This is the bug the user reported!")

# Scenario 4: Chars NOT on same page (truly cross-page)
print("\n" + "=" * 60)
print("TEST 4: Cross-page chars (王 on page 1, 麻+子 on page 2)")
print("=" * 60)

se4 = SearchEngine()
se4.add_ocr_results(0, [{'text': '王'}, {'text': '张三'}])
se4.add_ocr_results(1, [{'text': '麻'}, {'text': '子'}, {'text': '李四'}])
se4.add_ocr_results(2, [{'text': '王'}, {'text': '麻'}, {'text': '子'}, {'text': '王麻子'}])

print("\n--- Search '王麻子' ---")
r = se4.search('王麻子')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

print("\n--- Search '王' ---")
r = se4.search('王')
for item in r:
    print(f"  Page {item['page']}: [{item['source']}] {item['text'][:60]}")

print("\n✅ Tests complete")
